python main.py Instanca1 1
python main.py Instanca2 1
python main.py Instanca3 1
python main.py Instanca1 5
python main.py Instanca2 5
python main.py Instanca3 5
python main.py Instanca1 10
python main.py Instanca2 10
python main.py Instanca3 10
